### ISSUE TITLE
Crashes on init

### ISSUE THREAD

**Issue by kabo** [PhotoBackup/server-node#3]
I keep getting this error when trying to init. It doesn't matter what password I type in, there's always an out of range error, with the numbers being different.

```
$ photobackup init
? The directory where to put the pictures (should be writable by the server you use): /some/path
? Owner of the directory: nobody
? The server password: **************
readline.js:1032
            throw err;
            ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 10. Received 12
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32BE (internal/buffer.js:196:5)
    at Function.WordArray.fromBuffer (/usr/lib/node_modules/photobackup/node_modules/sha512/lib/word-array.js:95:19)
    at subtype.init.finalize (/usr/lib/node_modules/photobackup/node_modules/sha512/lib/cryptojs.js:273:33)
    at /usr/lib/node_modules/photobackup/node_modules/sha512/lib/cryptojs.js:300:35
    at module.exports.completed (/usr/lib/node_modules/photobackup/init.js:57:33)
    at module.exports.PromptUI.onCompletion (/usr/lib/node_modules/photobackup/node_modules/inquirer/lib/ui/prompt.js:56:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/lib/node_modules/photobackup/node_modules/rx-lite/rx.lite.js:1826:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/lib/node_modules/photobackup/node_modules/rx-lite/rx.lite.js:1763:14)
    at AnonymousObserver.tryCatcher (/usr/lib/node_modules/photobackup/node_modules/rx-lite/rx.lite.js:537:29)
```

Node 10.15.0, Debian Stretch.

**Comment by stephanepechard** [comment]
Thanks for filing a bug, I'll try to look at it soon.
